### ISSUE TITLE
Нужно использовать gitignore для Visual studio

### ISSUE THREAD

**Issue by alexeychernykh** [DarkMoonLi/practic#1]
https://github.com/DarkMoonLi/practic/blob/f9cbbb347e53c02afed23672b2c10b635d0cbe2b/Lab2/.gitignore#L1

Он предлагается при создании нового репизитория
Bin файлов не должно быть в репозитории. Должны быть только исходники.

**Comment by DarkMoonLi** [comment]
хорошо, попробую еще раз перезагрузить и разобраться получше,
