### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by YegorMan** [DarkMoonLi/practic#5]
https://github.com/DarkMoonLi/practic/blob/47963e94f1275235f9a5f752d4dfa1e4c72ac4af/.gitignore#L1

Судя по коммиту, .gitignore был добавлен после коммита кода, из-за чего в репозитории остались ненужные папки (obj, debug). Необходимо привести содержимое репозитория к чистому виду без лишних файлов и папок в соответствии с .gitignore

**Comment by DarkMoonLi** [comment]
спасибо
