### ISSUE TITLE
Именование переменных нужно camelCase

### ISSUE THREAD

**Issue by alexeychernykh** [DarkMoonLi/practic#7]
https://github.com/DarkMoonLi/practic/blob/c9981ed551a0f10d8b25d5c594fbd4933f943a39/Lab2/UniversityModel/Program.cs#L18

**Comment by DarkMoonLi** [comment]
Хорошо, переделаю, спасибо за недочет

**Comment by DarkMoonLi** [comment]
доброе время суток, изменение свойств в PrintStudioInfo.cs и IStudent.cs, т.е убраны Set перед свойствами(SetName-->Name), удалено неиспользуемое свойство GetInfoStudent. Изменены надписи переменных (key_down-->keyDown как параметры, key_down-->KeyDown как поля.)

**Comment by DarkMoonLi** [comment]
и я чуть-чуть накосячил, внес изменения коммитом "изменение", а оставшуюся часть этим "изменение свойств в PrintStudioInfo.cs и IStudent.cs, т.е убраны Set перед свойствами(SetName-->Name), удалено неиспользуемое свойство GetInfoStudent. Изменены надписи переменных (key_down-->keyDown как параметры, key_down-->KeyDown как поля.)".
Ветка была создана новая для pull-request(copyMaster--->master). Можно ли как-то вернуть ветку к пустому состоянию или легче удалить и заново создать? восстановление коммита не знаю, сработает или нет, потому что на момент создания его не было по идее

**Comment by alexeychernykh** [comment]
Сейчас неправильно, camelCase для переменных, PascalCase для публичных полей, свойств и методов.
Например, так правильно keyDown.Answer = "work";

**Comment by DarkMoonLi** [comment]
Хорошо, спасибо, обязательно попробую и переделаю

**Comment by DarkMoonLi** [comment]
доброе время суток, а можно ли сделать pull request без дополнительной ветки? у меня есть 2 ветки master и copyMaster. pull request одобряется только, когда делаю его из copyMaster в master, а если из master в master  не получается,

**Comment by alexeychernykh** [comment]
Из master в master нельзя сделать pull реквест. Пулл реквест делается из какой то ветки, которая была сделана из master и в неё добавлены камиты. Отдельная ветка в этом случае обязательна. Можете почитать про feature-branch.

**Comment by DarkMoonLi** [comment]
Спасибо большое)
